"""sync_cli.py — CLI version: audio→text & text→audio with output in LRC format.

Usage:
    # Audio → text + LRC
    python sync_cli.py transcribe input.mp3 --lang zh

    # Text → audio + LRC (estimated timestamps)
    python sync_cli.py synthesize "The weather is nice today." --voice nova

    # Text → audio + LRC (precise timestamps via second Whisper pass)
    python sync_cli.py synthesize "The weather is nice." --precise

Dependencies:
    pip install openai
"""

import os
import sys
import argparse
import json
import re
import tempfile
import base64
from pathlib import Path


def get_client():
    try:
        from openai import OpenAI
    except ImportError:
        sys.exit("❌ Please install openai: pip install openai")
    key = os.environ.get("OPENAI_API_KEY")
    if not key:
        sys.exit("❌ Please set the OPENAI_API_KEY environment variable")
    return OpenAI(api_key=key)


# ─── LRC format generation ──────────────────────────────────────────────────────
def to_lrc(segments: list[dict]) -> str:
    """Convert a segment list to standard LRC format."""
    lines = []
    lines.append("[ar: SyncLyric]")
    lines.append("[al: Generated by AI]")
    lines.append("[by: sync_cli.py]")
    lines.append("")
    for seg in segments:
        t = seg["start"]
        m = int(t // 60)
        s = t % 60
        tag = f"[{m:02d}:{s:05.2f}]"
        lines.append(f"{tag}{seg['text']}")
    return "\n".join(lines)


# ─── STT ──────────────────────────────────────────────────────────────────────
def cmd_transcribe(args):
    client = get_client()
    audio_path = Path(args.file)
    if not audio_path.exists():
        sys.exit(f"❌ File not found: {audio_path}")

    print(f"🎙 Transcribing: {audio_path.name} …")
    with open(audio_path, "rb") as f:
        response = client.audio.transcriptions.create(
            model="whisper-1",
            file=f,
            language=args.lang or None,
            response_format="verbose_json",
            timestamp_granularities=["word", "segment"],
        )

    # Format results
    words = []
    if hasattr(response, "words") and response.words:
        for w in response.words:
            words.append({"word": w.word, "start": round(w.start, 3), "end": round(w.end, 3)})

    segments = []
    if hasattr(response, "segments") and response.segments:
        for seg in response.segments:
            seg_words = []
            if hasattr(seg, "words") and seg.words:
                for w in seg.words:
                    seg_words.append({"word": w.word, "start": round(w.start, 3), "end": round(w.end, 3)})
            segments.append({
                "text": seg.text.strip(),
                "start": round(seg.start, 3),
                "end": round(seg.end, 3),
                "words": seg_words,
            })

    result = {
        "text": response.text,
        "words": words,
        "segments": segments,
        "duration": getattr(response, "duration", None),
    }

    # Save JSON
    json_out = audio_path.with_suffix(".json")
    json_out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"✅ JSON 已保存: {json_out}")

    # Save LRC
    if segments:
        lrc_out = audio_path.with_suffix(".lrc")
        lrc_out.write_text(to_lrc(segments), encoding="utf-8")
        print(f"✅ LRC saved: {lrc_out}")

    # Console preview
    print(f"\n📜 Transcribed text ({len(words)} words):")
    print(response.text)
    print(f"\n⏱ Duration: {result['duration']:.1f}s")


# ─── TTS ──────────────────────────────────────────────────────────────────────
def cmd_synthesize(args):
    client = get_client()
    text   = args.text
    voice  = args.voice
    speed  = args.speed
    model  = args.model

    print(f"🔊 Synthesizing (voice={voice}, speed={speed}×) …")
    tts_resp = client.audio.speech.create(
        model=model,
        voice=voice,
        input=text,
        speed=speed,
        response_format="mp3",
    )
    audio_bytes = tts_resp.content

    # Output audio file
    out_audio = Path(args.output or "output.mp3")
    out_audio.write_bytes(audio_bytes)
    print(f"✅ Audio saved: {out_audio}")

    # Timestamps
    if args.precise:
        print("🔍 Precise mode: using Whisper re-transcription for timestamps …")
        with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tmp:
            tmp.write(audio_bytes)
            tmp_path = tmp.name
        try:
            with open(tmp_path, "rb") as f:
                trans = client.audio.transcriptions.create(
                    model="whisper-1",
                    file=f,
                    response_format="verbose_json",
                    timestamp_granularities=["word", "segment"],
                )
        finally:
            os.unlink(tmp_path)

        segments = []
        if hasattr(trans, "segments") and trans.segments:
            for seg in trans.segments:
                seg_words = []
                if hasattr(seg, "words") and seg.words:
                    for w in seg.words:
                        seg_words.append({"word": w.word, "start": round(w.start, 3), "end": round(w.end, 3)})
                segments.append({
                    "text": seg.text.strip(),
                    "start": round(seg.start, 3),
                    "end": round(seg.end, 3),
                    "words": seg_words,
                })
        words = []
        if hasattr(trans, "words") and trans.words:
            for w in trans.words:
                words.append({"word": w.word, "start": round(w.start, 3), "end": round(w.end, 3)})
    else:
        print("⚡ Fast mode: estimate timestamps by character ratio (use --precise for better accuracy)")
        estimated = _estimate_timestamps(text, speed)
        segments  = estimated["segments"]
        words     = estimated["words"]

    result = {"text": text, "words": words, "segments": segments}

    json_out = out_audio.with_suffix(".json")
    json_out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"✅ JSON saved: {json_out}")

    if segments:
        lrc_out = out_audio.with_suffix(".lrc")
        lrc_out.write_text(to_lrc(segments), encoding="utf-8")
        print(f"✅ LRC saved: {lrc_out}")


# ─── Timestamp estimation (matches server.py) ───────────────────────────────────
def _estimate_timestamps(text: str, speed: float = 1.0) -> dict:
    chinese_chars = len(re.findall(r'[\u4e00-\u9fff]', text))
    is_chinese    = chinese_chars / max(len(text), 1) > 0.3

    if is_chinese:
        chars_per_sec = 3.5 * speed
    else:
        chars_per_sec = 14.0 * speed

    total_chars = max(len(text), 1)
    total_secs  = total_chars / chars_per_sec

    token_list = list(text) if is_chinese else text.split()
    words_out  = []
    cursor     = 0.0
    for token in token_list:
        if not token.strip():
            continue
        duration = (len(token) / total_chars) * total_secs
        words_out.append({"word": token, "start": round(cursor, 3), "end": round(cursor + duration, 3)})
        cursor += duration

    split_pat  = r'([，。！？；\n])' if is_chinese else r'([,\.\!\?;\n])'
    raw_segs   = re.split(split_pat, text)
    segs_out   = []
    cur2       = 0.0
    buf_txt    = ""
    for part in raw_segs:
        if not part:
            continue
        seg_dur = (len(part) / total_chars) * total_secs
        is_punc = bool(re.match(r'^[，。！？；,\.\!\?;\n]$', part))
        if is_punc:
            buf_txt += part
            if buf_txt.strip():
                segs_out.append({"text": buf_txt.strip(), "start": round(cur2, 3), "end": round(cur2 + seg_dur, 3), "words": []})
                cur2    += seg_dur
                buf_txt  = ""
        else:
            buf_txt += part
        if not is_punc:
            cur2 += seg_dur
    if buf_txt.strip():
        segs_out.append({"text": buf_txt.strip(), "start": round(cur2, 3), "end": round(total_secs, 3), "words": []})

    return {"words": words_out, "segments": segs_out, "duration": round(total_secs, 3)}


# ─── CLI ──────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Audio → text & text → audio (lyric sync)")
    sub    = parser.add_subparsers(dest="cmd", required=True)

    # transcribe
    p_tr = sub.add_parser("transcribe", help="Audio file → text + LRC")
    p_tr.add_argument("file", help="Path to the audio file")
    p_tr.add_argument("--lang", default="zh", help="Language code, e.g. zh/en/ja (default zh)")

    # synthesize
    p_sy = sub.add_parser("synthesize", help="Text → audio + LRC")
    p_sy.add_argument("text",   help="Text to synthesize")
    p_sy.add_argument("--output",  default="output.mp3", help="Output audio file name (default output.mp3)")
    p_sy.add_argument("--voice",   default="nova",       choices=["alloy","echo","fable","onyx","nova","shimmer"])
    p_sy.add_argument("--speed",   type=float, default=1.0, help="Speech speed (0.5-2.0, default 1.0)")
    p_sy.add_argument("--model",   default="tts-1",      choices=["tts-1","tts-1-hd"])
    p_sy.add_argument("--precise", action="store_true",  help="Use Whisper to get precise timestamps")

    args = parser.parse_args()
    if   args.cmd == "transcribe": cmd_transcribe(args)
    elif args.cmd == "synthesize": cmd_synthesize(args)


if __name__ == "__main__":
    main()
